.PHONY: clean All

All:
	@echo "----------Building project:[ FL1 - Debug ]----------"
	@cd "FL1" && "$(MAKE)" -f  "FL1.mk"
clean:
	@echo "----------Cleaning project:[ FL1 - Debug ]----------"
	@cd "FL1" && "$(MAKE)" -f  "FL1.mk" clean
