.PHONY: clean All

All:
	@echo "----------Building project:[ tic_tac_toe - Debug ]----------"
	@cd "tic_tac_toe" && "$(MAKE)" -f  "tic_tac_toe.mk" && "$(MAKE)" -f  "tic_tac_toe.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ tic_tac_toe - Debug ]----------"
	@cd "tic_tac_toe" && "$(MAKE)" -f  "tic_tac_toe.mk" clean
