.PHONY: clean All

All:
	@echo "----------Building project:[ memory - Debug ]----------"
	@cd "memory" && "$(MAKE)" -f  "memory.mk" && "$(MAKE)" -f  "memory.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ memory - Debug ]----------"
	@cd "memory" && "$(MAKE)" -f  "memory.mk" clean
