.PHONY: clean All

All:
	@echo "----------Building project:[ graphicdislpay - Debug ]----------"
	@cd "graphicdislpay" && "$(MAKE)" -f  "graphicdislpay.mk" && "$(MAKE)" -f  "graphicdislpay.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ graphicdislpay - Debug ]----------"
	@cd "graphicdislpay" && "$(MAKE)" -f  "graphicdislpay.mk" clean
